### ISSUE TITLE
plot() method show two subplots

### ISSUE THREAD

**Issue by jermaine1ronquillo** [oopnet/oopnet#38]
## Checks
- [x] I added a descriptive title to this issue
- [ ] I have searched (Google, GitHub) for similar issues and couldn't find anything
- [ ] I have read and followed the docs and still think this is a bug

# Bug Description
Using the plot() method return two subplots.

# Steps to Reproduce
network.plot()
network2.plot(nodes=p.iloc[1], links=f.iloc[1], fignum=0, robust=True)

# Expected Behavior
If this is the default of plot(), how will the second plot be removed?

# Screenshots
![image](https://user-images.githubusercontent.com/15191328/188198913-a590dfff-2e84-492c-b96a-6addd4d4f1eb.png)
![image](https://user-images.githubusercontent.com/15191328/188198959-5a6e1967-f23e-46b6-a130-79e479aa567d.png)

# Additional context

**Comment by tiuri101** [comment]
Thank you for the issue!

This is not a bug in OOPNET but a general "issue" with matplotlib plots in jupyter notebooks, see for instance [this `statsmodels` issue](https://github.com/statsmodels/statsmodels/issues/1265) or [this stack overflow post](https://stackoverflow.com/q/58792264/16748447). The latter one also shows several options how to deal with this.

Closing the issue since there is nothing to fix.
